### ISSUE TITLE
From Trello to GitHub Issues

### ISSUE THREAD

**Issue by ghost** [slchackers/SLCH#1]
@baens For SLCH, I plan to make use of GitHub issues and discontinue the use of Trello.  Any objections?  GitHub is not as visually appealing but integration with the repository and easy access by users are a few of many benefits I see.

**Comment by baens** [comment]
That makes sense to me!

**Comment by nobleach** [comment]
I'm used to this interface for a few other projects, so no complaints from this part of the peanut gallery.

**Comment by ghost** [comment]
Jolly good!
