### ISSUE TITLE
Go + PostgreSQL = ?

### ISSUE THREAD

**Issue by ghost** [slchackers/SLCH#2]
@baens Tell me more!

**Comment by nobleach** [comment]
https://github.com/nobleach/go-geocoder/blob/master/main.go

**Comment by baens** [comment]
Patients is the most boring virtue! :P tomorrow it's my goal for repo setup. Along with a pull request for a readme and feature specification.

**Comment by ghost** [comment]
Lack of pep is often mistaken for patience.  - Kin Hubbard 

Sounds great, I'm excited about this project!

@nobleach Thank you for sharing your go-geocoder!
